version: 2
updates:
  - package-ecosystem: "shell" # For Shell scripts
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "lua" # For Lua scripts
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # For CSS (assuming CSS is managed by npm)
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker" # For Dockerfiles
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
