# These are supported funding model platforms

github: OfficialV4NT, Jeyso215
patreon: V4NT
open_collective: 
ko_fi: https://ko-fi.com/jeyso
liberapay: https://liberapay.com/Jeyso/
custom: 45K3QyhGGysAGDvFhGnYne3qcajeGmjRXXGZ8p3LeWBxFgiDkZ7XhLuNxDB5QsjS8ySQtHmjGaoWc6Vg5wtfaPmoCHRDmC4
