version: '3.8'

services:
  porninvidious:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
    restart: unless-stopped