name: Dependabot

on:
  schedule:
    - cron: '0 0 * * 1'  # Runs every Monday at midnight UTC
  push:
    paths:
      - '.github/dependabot.yml'

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Dependabot
      run: npx dependabot
